---
title: "Ithaka"
author: "by Constantine Cavafy"
output: html_document
---

| As you set out for Ithaka
| hope the voyage is a long one,
| full of adventure, full of discovery.
| Laistrygonians and Cyclops,
| angry Poseidon—don’t be afraid of them:
| you’ll never find things like that on your way
| as long as you keep your thoughts raised high,
| as long as a rare excitement
| stirs your spirit and your body.
| Laistrygonians and Cyclops,
| wild Poseidon—you won’t encounter them
| unless you bring them along inside your soul,
| unless your soul sets them up in front of you.


| Hope the voyage is a long one.
| May there be many a summer morning when,
| with what pleasure, what joy,
| you come into harbors seen for the first time;
| may you stop at Phoenician trading stations
| to buy fine things,
| mother of pearl and coral, amber and ebony,
| sensual perfume of every kind—
| as many sensual perfumes as you can;
| and may you visit many Egyptian cities
| to gather stores of knowledge from their scholars.
 
| Keep Ithaka always in your mind.
| Arriving there is what you are destined for.
| But do not hurry the journey at all.
| Better if it lasts for years,
| so you are old by the time you reach the island,
| wealthy with all you have gained on the way,
| not expecting Ithaka to make you rich.


| Ithaka gave you the marvelous journey.
| Without her you would not have set out.
| She has nothing left to give you now.


| And if you find her poor, Ithaka won’t have fooled you.
| Wise as you will have become, so full of experience,
| you will have understood by then what these Ithakas mean.
